### ISSUE TITLE
Keeping track of interaction with the mock/patch

### ISSUE THREAD

**Issue by tk3369** [invenia/Mocking.jl#72]
It would be nice if we can tell how many times a patch was called after exercising a test.  As a reference, see Mockito's documentation at https://static.javadoc.io/org.mockito/mockito-core/3.1.0/org/mockito/Mockito.html#7

Mockito can also capture arguments that are passed to the mock.  Then, as part of the verification step, we can check that against our expectation.
See https://static.javadoc.io/org.mockito/mockito-core/3.1.0/org/mockito/Mockito.html#finding_redundant_invocations

**Comment by oxinabox** [comment]
You can do this by assigning variables inside your patch to track its inputs seen (i.e using s closure).

I agree it would be nice to have this.
To my mind Mocking is linked to the idea of testsets that are structured as:

- setting Setting up expectations (in defining your patches),
- running your code (with the mocking inplace)
- testing that those expectations were used and thus that the interaction between the tested component and the mocked out components were as expected.

I previously have argued it belongs in a seperate package, but I am less sure these days.

You can do it with [ExpectationStubs.jl](
https://github.com/oxinabox/ExpectationStubs.jl)
I recently tried using it with Mocking.jl, it works.
(It had [other issues](https://github.com/oxinabox/ExpectationStubs.jl/issues/14), but not related to its asserting about what inputs stubs saw)

**Comment by tk3369** [comment]
Nice! 👍   I didn't know ExpectationStubs exists.   Looks like it would work. I will give that a try!
