### ISSUE TITLE
Factor some utilities out into a separate package

### ISSUE THREAD

**Issue by MasonProtter** [invenia/Mocking.jl#77]
It was brought to my attention that your implementation of `splitdef` and `combinedef` is preferable to the one found in MacroTools.jl. I think a separate package for those utilities and maybe a few others would be appreciated so I can depend on those instead of the entirety of Mocking.

**Comment by tk3369** [comment]
Really? How?  Perhaps better to contribute back to MacroTools?

**Comment by omus** [comment]
> Really? How? Perhaps better to contribute back to MacroTools?

The versions in this package handle more syntax than MacroTools.jl and are more performant. See 
https://github.com/invenia/Mocking.jl/pull/66

I'll make a PR to MacroTools.jl with the improved version but my personal preference would be to have this functionality as a completely separate package as I'm trying to keep the dependency tree for Mocking.jl very light.

**Comment by MasonProtter** [comment]
If it's factored into a separate package, we can just submit a PR to MacroTools asking it to depend on that package. MacroTools already has a million to dependancies, so what's one more?

**Comment by oxinabox** [comment]
(DataStructures.jl only has 1 dependency -- OrderedCollections.jl)

But yes,I would like this in a seperate package. Then one can use this + MLStyle instead of MacroTools for most features.

**Comment by omus** [comment]
I'll make this as a separate package. I guess it can stay in the Invenia github org as I'm not seeing a suitable Julia org.

**Comment by omus** [comment]
Still working on it but I've pushed some code: https://github.com/invenia/ExprTools.jl

**Comment by omus** [comment]
ExprTools.jl is currently awaiting registration: https://github.com/JuliaRegistries/General/pull/7999

**Comment by omus** [comment]
Package is registered
