### ISSUE TITLE
Mocking only specific call sites when calling a top level function

### ISSUE THREAD

**Issue by fchorney** [invenia/Mocking.jl#99]
Here's my situation. I have a package where I am mocking say function `foo` in various locations. Let's say `func_1` and `func_2` both call `foo` and both have `@mock foo(...)`.

In my tests, I test each function individually, and this works fine as I can patch `foo` or not patch `foo` when I need to.

The issue arrises when I want to test a top level function but only want to patch `foo` in one of the two functions. 

Both calls to `foo` use the same signature, and for the purpose of this query, let's say that I can't change that. It would be nice if we could potentially designate different call sites as needing to be mocked when we apply. 

The syntax here I don't think really works but for purposes of illustration maybe something like

```julia
function func_1()
    @mock 1 foo(...)
end

function func_2()
    @mock 2 foo(...)
end
```

then in the tests you could have something like the following, which would not mock the `foo` in `func_2`

```julia
apply(foo_patch; ignore=[2]) do
    ...
end
```

Or if there is already some way to achieve this, I could not find it.

**Comment by fchorney** [comment]
Some other solutions I was given just to have that information here:

1. check the argument within the patched version and use that info to choose whether to do the original or mocked behaviour
2. mock at a higher level

Option 1 actually solved my issue, but I'm wondering if this designation idea might have some use. I'll leave this up for now to see if it spawns any sort of discussion or anything. I imagine this issue might not really pop up very often.

**Comment by rofinn** [comment]
Yeah, I think the options you were given make the most sense. The only thing I think Mocking could really do is codify option one with some extra syntax (e.g., condition expression to run, file & line number, calling function name).

**Comment by fchorney** [comment]
Going to close this as option 1 solved my issue, and it doesn't seem like there's a good overall want for another solution.
